#pragma once

#include "Program.hpp"

#include "ASTElement.hpp"

#include "Expression.hpp"
#include "PlusExpression.hpp"
#include "MinusExpression.hpp"
#include "StarExpression.hpp"
#include "SlashExpression.hpp"
#include "ProcExpression.hpp"
#include "AndExpression.hpp"
#include "OrExpression.hpp"
#include "LessExpression.hpp"
#include "GreatExpression.hpp"
#include "EqualExpression.hpp"
#include "ArrayExpression.hpp"
#include "LengthExpression.hpp"
#include "NewArrayExpression.hpp"
#include "NotExpression.hpp"
#include "NumberExpression.hpp"
#include "BoolExpression.hpp"
#include "IdentifierExpression.hpp"
#include "UnaryMinusExpression.hpp"
#include "ParenExpression.hpp"

#include "Statement.hpp"
#include "StatementsList.hpp"
#include "IfStatement.hpp"
#include "IfElseStatement.hpp"
#include "WhileStatement.hpp"
#include "ReturnStatement.hpp"
#include "AssertStatement.hpp"
#include "OutputStatement.hpp"
#include "BraceStatement.hpp"
#include "AssignStatement.hpp"
#include "DeclarationStatement.hpp"

#include "Lvalue.hpp"
#include "IdentifierLvalue.hpp"
#include "ElementLvalue.hpp"

#include "Type.hpp"
#include "ArrayType.hpp"
#include "SimpleType.hpp"

#include "Declaration.hpp"